dist: xenial
sudo: required

language: cpp

addons:
  apt:
    packages:
      - wine

branches:
  only:
    - master

script:
# Fetch toolchain, set variables
  - export WINEDEBUG=-all
  - export CEDEV=~/CEdev
  - export PATH=$CEDEV/bin/:$PATH
  - git clone --recursive https://github.com/CE-Programming/toolchain.git
  - cd toolchain
  - make
  - make install
  - make release
  - make release-libs
  - export AUTOTESTER_LIBS_DIR=$(pwd)/clibraries
  - cd ..
# Build ICE
  - make
# Build CEmu core and autotester_cli
  - git clone --recursive -b latest-stable --depth 1 https://github.com/CE-Programming/CEmu.git
  - make -C CEmu/core -j4
  - make -C CEmu/tests/autotester -j4
  - export PATH=$(pwd)/CEmu/tests/autotester:$PATH
# Grab ROM for tests below
  - export ROM_FILE_NAME=84pce_515_53.rom
  - curl -s https://tiplanet.org/scripts/travis/$ROM_FILE_NAME 2>/dev/null > $ROM_FILE_NAME
  - export AUTOTESTER_ROM=$(pwd)/$ROM_FILE_NAME
# Test tests
  - RESULT=0; for f in tests/*/*.json; do echo "Launching autotester on $f"; autotester "$f"; RESULT=`expr $RESULT + $?`; done; return $RESULT

notifications:
  irc:
    channels:
      - "irc.choopa.net#icedev"
    on_success: change
    on_failure: always
    skip_join: true